#version: '3.8'
services:
  # Django App 
  backend_cart:
    container_name: boomslag_ms_cart
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db_cart
      - redis
  cart_queue:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db_cart
  # PostgreSQL
   # Database (PostgreSQL)
  db_cart:
   image: postgres
   container_name: django_cart_api_postgresql
   restart: always
   environment:
      POSTGRES_DB: solopython_cart_db
      POSTGRES_USER: solopython
      POSTGRES_PASSWORD: postgres
   ports:
    - 5433:5432
   volumes:
    - .dbdata:/var/lib/postgresql
  #Redis
  redis:
    image: redis
    container_name: django_cart_api_redis
    ports:
      - 6380:6379