# Generated by Django 3.2.16 on 2024-08-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240822_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='agreed',
            field=models.BooleanField(default=False),
        ),
    ]
