#version: '3.8'
services:
  # Django App 
  backend_wishlist:
    container_name: boomslag_ms_wishlist
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8006"
    ports:
      - 8006:8006
    volumes:
      - .:/app
    depends_on:
      - db_wishlist
      - redis
  wishlist_queue:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db_wishlist
  # PostgreSQL
   # Database (PostgreSQL)
  db_wishlist:
   image: postgres
   container_name: django_wishlist_api_postgresql
   restart: always
   environment:
      POSTGRES_DB: solopython_wishlist_db
      POSTGRES_USER: solopython
      POSTGRES_PASSWORD: postgres
   ports:
    - 5438:5432
   volumes:
    - .dbdata:/var/lib/postgresql
  #Redis
  redis:
    image: redis
    container_name: django_wishlist_api_redis
    ports:
      - 6385:6379